[package]
name = "alloc_counter_macro"
version = "0.0.0"
authors = ["The SiO4 Project Developers <https://gitlab.com/sio4>"]
edition = "2018"
publish = false
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies.syn]
version = "*"
features = ["full"]

[dependencies.proc-quote]
version = "*"

[dependencies.proc-macro2]
version = "*"
